# Generated by Django 4.2.6 on 2023-10-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('smoke_level', models.IntegerField()),
            ],
        ),
    ]
