# Generated by Django 4.2.6 on 2023-10-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='smoke_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
